name: Continuous Integration

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  my_first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Show Node.js version
        run: node --version

      - name: Install Dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Test application
        run: npm test